// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vgvxbgfyrabvbksmniba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZndnhiZ2Z5cmFidmJrc21uaWJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM5NDc4MDYsImV4cCI6MjA0OTUyMzgwNn0.3waa7RsOzU-vRTdBxJ_U7xuRsOoI8rgrKsibs7htt74";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);